### ISSUE TITLE
Pin connections

### ISSUE THREAD

**Issue by Thoky81** [gnlcosta/scale#1]
Hi,

I have upload your code but I am not sure which pins I should use to connect the rotary encoder and OLED panel. Please suggest. Thanks

**Comment by gnlcosta** [comment]
Hi,
Encoder: 2(DT), 3(CLK), 4(SW)
Display (I2C): A4(SDA), A5(SCK)
HX711: A1(DT), A2(SCK)

**Comment by Thoky81** [comment]
Hi,
thanks it looks like the connection is working but I just see a 0.0 g on the display even if I load the weight and every 10 seconds it jumps to some numbers but very quickly returns to zero again. In the code I have seen that there should be a menu or something? Or how should I for example use the rotary encoder to tare it.
Thanks for advice

**Comment by gcmitec** [comment]
If you push the rotary encorde's button you can enter in the menu.

**Comment by Thoky81** [comment]
I did tried this but no success. I will also try to use another one.

**Comment by gnlcosta** [comment]
Hi, 
I checked with last version of Arduino IDE and libraries and Display and the encoder (=>menu) work.
Using the menu you can calibrate the HX711+load cell.
I don't have (now) the possibility to check the HX711 the load cell.

**Comment by Thoky81** [comment]
Hi,
OK it working now 😀
I have checked everything and it was a bad GND wire on encoder.
So thanks a lot for your help.

**Comment by Thoky81** [comment]
Oh and one more thing. You have a load cell max 20000g. What everything should I change in the code in order to set this to max 5000 as per my load cell max value. I can see in the menu option to change it but it rotating from 20000 -> 5000 taking long time 😀
Thanks

**Comment by gcmitec** [comment]
Hi,
you have to change load_cel_max in the line 59.

**Comment by Thoky81** [comment]
Hi,

OK I got it. I had to erase the EEPROM and now working.

Thanks
